// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ARRAYOFFLOAT64_COMM_DATALAYER_H_
#define FLATBUFFERS_GENERATED_ARRAYOFFLOAT64_COMM_DATALAYER_H_

#include "flatbuffers/flatbuffers.h"

namespace comm {
namespace datalayer {

struct ArrayOfFloat64;
struct ArrayOfFloat64Builder;
struct ArrayOfFloat64T;

struct ArrayOfFloat64T : public flatbuffers::NativeTable {
  typedef ArrayOfFloat64 TableType;
  std::vector<double> value{};
};

struct ArrayOfFloat64 FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ArrayOfFloat64T NativeTableType;
  typedef ArrayOfFloat64Builder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<double> *value() const {
    return GetPointer<const flatbuffers::Vector<double> *>(VT_VALUE);
  }
  flatbuffers::Vector<double> *mutable_value() {
    return GetPointer<flatbuffers::Vector<double> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyVector(value()) &&
           verifier.EndTable();
  }
  ArrayOfFloat64T *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ArrayOfFloat64T *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<ArrayOfFloat64> Pack(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfFloat64T* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ArrayOfFloat64Builder {
  typedef ArrayOfFloat64 Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<double>> value) {
    fbb_.AddOffset(ArrayOfFloat64::VT_VALUE, value);
  }
  explicit ArrayOfFloat64Builder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ArrayOfFloat64> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ArrayOfFloat64>(end);
    return o;
  }
};

inline flatbuffers::Offset<ArrayOfFloat64> CreateArrayOfFloat64(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<double>> value = 0) {
  ArrayOfFloat64Builder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<ArrayOfFloat64> CreateArrayOfFloat64Direct(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<double> *value = nullptr) {
  auto value__ = value ? _fbb.CreateVector<double>(*value) : 0;
  return comm::datalayer::CreateArrayOfFloat64(
      _fbb,
      value__);
}

flatbuffers::Offset<ArrayOfFloat64> CreateArrayOfFloat64(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfFloat64T *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline ArrayOfFloat64T *ArrayOfFloat64::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ArrayOfFloat64T>(new ArrayOfFloat64T());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ArrayOfFloat64::UnPackTo(ArrayOfFloat64T *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = value(); if (_e) { _o->value.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->value[_i] = _e->Get(_i); } } }
}

inline flatbuffers::Offset<ArrayOfFloat64> ArrayOfFloat64::Pack(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfFloat64T* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateArrayOfFloat64(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<ArrayOfFloat64> CreateArrayOfFloat64(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfFloat64T *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const ArrayOfFloat64T* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _value = _o->value.size() ? _fbb.CreateVector(_o->value) : 0;
  return comm::datalayer::CreateArrayOfFloat64(
      _fbb,
      _value);
}

inline const comm::datalayer::ArrayOfFloat64 *GetArrayOfFloat64(const void *buf) {
  return flatbuffers::GetRoot<comm::datalayer::ArrayOfFloat64>(buf);
}

inline const comm::datalayer::ArrayOfFloat64 *GetSizePrefixedArrayOfFloat64(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<comm::datalayer::ArrayOfFloat64>(buf);
}

inline ArrayOfFloat64 *GetMutableArrayOfFloat64(void *buf) {
  return flatbuffers::GetMutableRoot<ArrayOfFloat64>(buf);
}

inline bool VerifyArrayOfFloat64Buffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<comm::datalayer::ArrayOfFloat64>(nullptr);
}

inline bool VerifySizePrefixedArrayOfFloat64Buffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<comm::datalayer::ArrayOfFloat64>(nullptr);
}

inline void FinishArrayOfFloat64Buffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<comm::datalayer::ArrayOfFloat64> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedArrayOfFloat64Buffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<comm::datalayer::ArrayOfFloat64> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<comm::datalayer::ArrayOfFloat64T> UnPackArrayOfFloat64(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<comm::datalayer::ArrayOfFloat64T>(GetArrayOfFloat64(buf)->UnPack(res));
}

inline std::unique_ptr<comm::datalayer::ArrayOfFloat64T> UnPackSizePrefixedArrayOfFloat64(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<comm::datalayer::ArrayOfFloat64T>(GetSizePrefixedArrayOfFloat64(buf)->UnPack(res));
}

}  // namespace datalayer
}  // namespace comm

#endif  // FLATBUFFERS_GENERATED_ARRAYOFFLOAT64_COMM_DATALAYER_H_
