// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ARRAYOFINT16_COMM_DATALAYER_H_
#define FLATBUFFERS_GENERATED_ARRAYOFINT16_COMM_DATALAYER_H_

#include "flatbuffers/flatbuffers.h"

namespace comm {
namespace datalayer {

struct ArrayOfInt16;
struct ArrayOfInt16Builder;
struct ArrayOfInt16T;

struct ArrayOfInt16T : public flatbuffers::NativeTable {
  typedef ArrayOfInt16 TableType;
  std::vector<int16_t> value{};
};

struct ArrayOfInt16 FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ArrayOfInt16T NativeTableType;
  typedef ArrayOfInt16Builder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<int16_t> *value() const {
    return GetPointer<const flatbuffers::Vector<int16_t> *>(VT_VALUE);
  }
  flatbuffers::Vector<int16_t> *mutable_value() {
    return GetPointer<flatbuffers::Vector<int16_t> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyVector(value()) &&
           verifier.EndTable();
  }
  ArrayOfInt16T *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ArrayOfInt16T *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<ArrayOfInt16> Pack(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfInt16T* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ArrayOfInt16Builder {
  typedef ArrayOfInt16 Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<int16_t>> value) {
    fbb_.AddOffset(ArrayOfInt16::VT_VALUE, value);
  }
  explicit ArrayOfInt16Builder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ArrayOfInt16> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ArrayOfInt16>(end);
    return o;
  }
};

inline flatbuffers::Offset<ArrayOfInt16> CreateArrayOfInt16(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<int16_t>> value = 0) {
  ArrayOfInt16Builder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<ArrayOfInt16> CreateArrayOfInt16Direct(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<int16_t> *value = nullptr) {
  auto value__ = value ? _fbb.CreateVector<int16_t>(*value) : 0;
  return comm::datalayer::CreateArrayOfInt16(
      _fbb,
      value__);
}

flatbuffers::Offset<ArrayOfInt16> CreateArrayOfInt16(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfInt16T *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline ArrayOfInt16T *ArrayOfInt16::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ArrayOfInt16T>(new ArrayOfInt16T());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ArrayOfInt16::UnPackTo(ArrayOfInt16T *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = value(); if (_e) { _o->value.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->value[_i] = _e->Get(_i); } } }
}

inline flatbuffers::Offset<ArrayOfInt16> ArrayOfInt16::Pack(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfInt16T* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateArrayOfInt16(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<ArrayOfInt16> CreateArrayOfInt16(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfInt16T *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const ArrayOfInt16T* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _value = _o->value.size() ? _fbb.CreateVector(_o->value) : 0;
  return comm::datalayer::CreateArrayOfInt16(
      _fbb,
      _value);
}

inline const comm::datalayer::ArrayOfInt16 *GetArrayOfInt16(const void *buf) {
  return flatbuffers::GetRoot<comm::datalayer::ArrayOfInt16>(buf);
}

inline const comm::datalayer::ArrayOfInt16 *GetSizePrefixedArrayOfInt16(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<comm::datalayer::ArrayOfInt16>(buf);
}

inline ArrayOfInt16 *GetMutableArrayOfInt16(void *buf) {
  return flatbuffers::GetMutableRoot<ArrayOfInt16>(buf);
}

inline bool VerifyArrayOfInt16Buffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<comm::datalayer::ArrayOfInt16>(nullptr);
}

inline bool VerifySizePrefixedArrayOfInt16Buffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<comm::datalayer::ArrayOfInt16>(nullptr);
}

inline void FinishArrayOfInt16Buffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<comm::datalayer::ArrayOfInt16> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedArrayOfInt16Buffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<comm::datalayer::ArrayOfInt16> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<comm::datalayer::ArrayOfInt16T> UnPackArrayOfInt16(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<comm::datalayer::ArrayOfInt16T>(GetArrayOfInt16(buf)->UnPack(res));
}

inline std::unique_ptr<comm::datalayer::ArrayOfInt16T> UnPackSizePrefixedArrayOfInt16(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<comm::datalayer::ArrayOfInt16T>(GetSizePrefixedArrayOfInt16(buf)->UnPack(res));
}

}  // namespace datalayer
}  // namespace comm

#endif  // FLATBUFFERS_GENERATED_ARRAYOFINT16_COMM_DATALAYER_H_
