// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ARRAYOFUINT16_COMM_DATALAYER_H_
#define FLATBUFFERS_GENERATED_ARRAYOFUINT16_COMM_DATALAYER_H_

#include "flatbuffers/flatbuffers.h"

namespace comm {
namespace datalayer {

struct ArrayOfUInt16;
struct ArrayOfUInt16Builder;
struct ArrayOfUInt16T;

struct ArrayOfUInt16T : public flatbuffers::NativeTable {
  typedef ArrayOfUInt16 TableType;
  std::vector<uint16_t> value{};
};

struct ArrayOfUInt16 FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ArrayOfUInt16T NativeTableType;
  typedef ArrayOfUInt16Builder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<uint16_t> *value() const {
    return GetPointer<const flatbuffers::Vector<uint16_t> *>(VT_VALUE);
  }
  flatbuffers::Vector<uint16_t> *mutable_value() {
    return GetPointer<flatbuffers::Vector<uint16_t> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyVector(value()) &&
           verifier.EndTable();
  }
  ArrayOfUInt16T *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ArrayOfUInt16T *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<ArrayOfUInt16> Pack(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfUInt16T* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ArrayOfUInt16Builder {
  typedef ArrayOfUInt16 Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<uint16_t>> value) {
    fbb_.AddOffset(ArrayOfUInt16::VT_VALUE, value);
  }
  explicit ArrayOfUInt16Builder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ArrayOfUInt16> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ArrayOfUInt16>(end);
    return o;
  }
};

inline flatbuffers::Offset<ArrayOfUInt16> CreateArrayOfUInt16(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<uint16_t>> value = 0) {
  ArrayOfUInt16Builder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<ArrayOfUInt16> CreateArrayOfUInt16Direct(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint16_t> *value = nullptr) {
  auto value__ = value ? _fbb.CreateVector<uint16_t>(*value) : 0;
  return comm::datalayer::CreateArrayOfUInt16(
      _fbb,
      value__);
}

flatbuffers::Offset<ArrayOfUInt16> CreateArrayOfUInt16(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfUInt16T *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline ArrayOfUInt16T *ArrayOfUInt16::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ArrayOfUInt16T>(new ArrayOfUInt16T());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ArrayOfUInt16::UnPackTo(ArrayOfUInt16T *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = value(); if (_e) { _o->value.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->value[_i] = _e->Get(_i); } } }
}

inline flatbuffers::Offset<ArrayOfUInt16> ArrayOfUInt16::Pack(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfUInt16T* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateArrayOfUInt16(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<ArrayOfUInt16> CreateArrayOfUInt16(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfUInt16T *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const ArrayOfUInt16T* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _value = _o->value.size() ? _fbb.CreateVector(_o->value) : 0;
  return comm::datalayer::CreateArrayOfUInt16(
      _fbb,
      _value);
}

inline const comm::datalayer::ArrayOfUInt16 *GetArrayOfUInt16(const void *buf) {
  return flatbuffers::GetRoot<comm::datalayer::ArrayOfUInt16>(buf);
}

inline const comm::datalayer::ArrayOfUInt16 *GetSizePrefixedArrayOfUInt16(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<comm::datalayer::ArrayOfUInt16>(buf);
}

inline ArrayOfUInt16 *GetMutableArrayOfUInt16(void *buf) {
  return flatbuffers::GetMutableRoot<ArrayOfUInt16>(buf);
}

inline bool VerifyArrayOfUInt16Buffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<comm::datalayer::ArrayOfUInt16>(nullptr);
}

inline bool VerifySizePrefixedArrayOfUInt16Buffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<comm::datalayer::ArrayOfUInt16>(nullptr);
}

inline void FinishArrayOfUInt16Buffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<comm::datalayer::ArrayOfUInt16> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedArrayOfUInt16Buffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<comm::datalayer::ArrayOfUInt16> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<comm::datalayer::ArrayOfUInt16T> UnPackArrayOfUInt16(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<comm::datalayer::ArrayOfUInt16T>(GetArrayOfUInt16(buf)->UnPack(res));
}

inline std::unique_ptr<comm::datalayer::ArrayOfUInt16T> UnPackSizePrefixedArrayOfUInt16(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<comm::datalayer::ArrayOfUInt16T>(GetSizePrefixedArrayOfUInt16(buf)->UnPack(res));
}

}  // namespace datalayer
}  // namespace comm

#endif  // FLATBUFFERS_GENERATED_ARRAYOFUINT16_COMM_DATALAYER_H_
