// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ARRAYOFSTRING_COMM_DATALAYER_H_
#define FLATBUFFERS_GENERATED_ARRAYOFSTRING_COMM_DATALAYER_H_

#include "flatbuffers/flatbuffers.h"

namespace comm {
namespace datalayer {

struct ArrayOfString;
struct ArrayOfStringBuilder;
struct ArrayOfStringT;

struct ArrayOfStringT : public flatbuffers::NativeTable {
  typedef ArrayOfString TableType;
  std::vector<std::string> value{};
};

struct ArrayOfString FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ArrayOfStringT NativeTableType;
  typedef ArrayOfStringBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *value() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_VALUE);
  }
  flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *mutable_value() {
    return GetPointer<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyVector(value()) &&
           verifier.VerifyVectorOfStrings(value()) &&
           verifier.EndTable();
  }
  ArrayOfStringT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ArrayOfStringT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<ArrayOfString> Pack(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfStringT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ArrayOfStringBuilder {
  typedef ArrayOfString Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> value) {
    fbb_.AddOffset(ArrayOfString::VT_VALUE, value);
  }
  explicit ArrayOfStringBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ArrayOfString> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ArrayOfString>(end);
    return o;
  }
};

inline flatbuffers::Offset<ArrayOfString> CreateArrayOfString(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> value = 0) {
  ArrayOfStringBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<ArrayOfString> CreateArrayOfStringDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *value = nullptr) {
  auto value__ = value ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*value) : 0;
  return comm::datalayer::CreateArrayOfString(
      _fbb,
      value__);
}

flatbuffers::Offset<ArrayOfString> CreateArrayOfString(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfStringT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline ArrayOfStringT *ArrayOfString::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ArrayOfStringT>(new ArrayOfStringT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ArrayOfString::UnPackTo(ArrayOfStringT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = value(); if (_e) { _o->value.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->value[_i] = _e->Get(_i)->str(); } } }
}

inline flatbuffers::Offset<ArrayOfString> ArrayOfString::Pack(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfStringT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateArrayOfString(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<ArrayOfString> CreateArrayOfString(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfStringT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const ArrayOfStringT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _value = _o->value.size() ? _fbb.CreateVectorOfStrings(_o->value) : 0;
  return comm::datalayer::CreateArrayOfString(
      _fbb,
      _value);
}

inline const comm::datalayer::ArrayOfString *GetArrayOfString(const void *buf) {
  return flatbuffers::GetRoot<comm::datalayer::ArrayOfString>(buf);
}

inline const comm::datalayer::ArrayOfString *GetSizePrefixedArrayOfString(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<comm::datalayer::ArrayOfString>(buf);
}

inline ArrayOfString *GetMutableArrayOfString(void *buf) {
  return flatbuffers::GetMutableRoot<ArrayOfString>(buf);
}

inline bool VerifyArrayOfStringBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<comm::datalayer::ArrayOfString>(nullptr);
}

inline bool VerifySizePrefixedArrayOfStringBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<comm::datalayer::ArrayOfString>(nullptr);
}

inline void FinishArrayOfStringBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<comm::datalayer::ArrayOfString> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedArrayOfStringBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<comm::datalayer::ArrayOfString> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<comm::datalayer::ArrayOfStringT> UnPackArrayOfString(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<comm::datalayer::ArrayOfStringT>(GetArrayOfString(buf)->UnPack(res));
}

inline std::unique_ptr<comm::datalayer::ArrayOfStringT> UnPackSizePrefixedArrayOfString(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<comm::datalayer::ArrayOfStringT>(GetSizePrefixedArrayOfString(buf)->UnPack(res));
}

}  // namespace datalayer
}  // namespace comm

#endif  // FLATBUFFERS_GENERATED_ARRAYOFSTRING_COMM_DATALAYER_H_
