// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ARRAYOFUINT32_COMM_DATALAYER_H_
#define FLATBUFFERS_GENERATED_ARRAYOFUINT32_COMM_DATALAYER_H_

#include "flatbuffers/flatbuffers.h"

namespace comm {
namespace datalayer {

struct ArrayOfUInt32;
struct ArrayOfUInt32Builder;
struct ArrayOfUInt32T;

struct ArrayOfUInt32T : public flatbuffers::NativeTable {
  typedef ArrayOfUInt32 TableType;
  std::vector<uint32_t> value{};
};

struct ArrayOfUInt32 FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ArrayOfUInt32T NativeTableType;
  typedef ArrayOfUInt32Builder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<uint32_t> *value() const {
    return GetPointer<const flatbuffers::Vector<uint32_t> *>(VT_VALUE);
  }
  flatbuffers::Vector<uint32_t> *mutable_value() {
    return GetPointer<flatbuffers::Vector<uint32_t> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyVector(value()) &&
           verifier.EndTable();
  }
  ArrayOfUInt32T *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ArrayOfUInt32T *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<ArrayOfUInt32> Pack(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfUInt32T* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ArrayOfUInt32Builder {
  typedef ArrayOfUInt32 Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<uint32_t>> value) {
    fbb_.AddOffset(ArrayOfUInt32::VT_VALUE, value);
  }
  explicit ArrayOfUInt32Builder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ArrayOfUInt32> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ArrayOfUInt32>(end);
    return o;
  }
};

inline flatbuffers::Offset<ArrayOfUInt32> CreateArrayOfUInt32(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<uint32_t>> value = 0) {
  ArrayOfUInt32Builder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<ArrayOfUInt32> CreateArrayOfUInt32Direct(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint32_t> *value = nullptr) {
  auto value__ = value ? _fbb.CreateVector<uint32_t>(*value) : 0;
  return comm::datalayer::CreateArrayOfUInt32(
      _fbb,
      value__);
}

flatbuffers::Offset<ArrayOfUInt32> CreateArrayOfUInt32(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfUInt32T *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline ArrayOfUInt32T *ArrayOfUInt32::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ArrayOfUInt32T>(new ArrayOfUInt32T());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ArrayOfUInt32::UnPackTo(ArrayOfUInt32T *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = value(); if (_e) { _o->value.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->value[_i] = _e->Get(_i); } } }
}

inline flatbuffers::Offset<ArrayOfUInt32> ArrayOfUInt32::Pack(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfUInt32T* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateArrayOfUInt32(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<ArrayOfUInt32> CreateArrayOfUInt32(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfUInt32T *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const ArrayOfUInt32T* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _value = _o->value.size() ? _fbb.CreateVector(_o->value) : 0;
  return comm::datalayer::CreateArrayOfUInt32(
      _fbb,
      _value);
}

inline const comm::datalayer::ArrayOfUInt32 *GetArrayOfUInt32(const void *buf) {
  return flatbuffers::GetRoot<comm::datalayer::ArrayOfUInt32>(buf);
}

inline const comm::datalayer::ArrayOfUInt32 *GetSizePrefixedArrayOfUInt32(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<comm::datalayer::ArrayOfUInt32>(buf);
}

inline ArrayOfUInt32 *GetMutableArrayOfUInt32(void *buf) {
  return flatbuffers::GetMutableRoot<ArrayOfUInt32>(buf);
}

inline bool VerifyArrayOfUInt32Buffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<comm::datalayer::ArrayOfUInt32>(nullptr);
}

inline bool VerifySizePrefixedArrayOfUInt32Buffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<comm::datalayer::ArrayOfUInt32>(nullptr);
}

inline void FinishArrayOfUInt32Buffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<comm::datalayer::ArrayOfUInt32> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedArrayOfUInt32Buffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<comm::datalayer::ArrayOfUInt32> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<comm::datalayer::ArrayOfUInt32T> UnPackArrayOfUInt32(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<comm::datalayer::ArrayOfUInt32T>(GetArrayOfUInt32(buf)->UnPack(res));
}

inline std::unique_ptr<comm::datalayer::ArrayOfUInt32T> UnPackSizePrefixedArrayOfUInt32(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<comm::datalayer::ArrayOfUInt32T>(GetSizePrefixedArrayOfUInt32(buf)->UnPack(res));
}

}  // namespace datalayer
}  // namespace comm

#endif  // FLATBUFFERS_GENERATED_ARRAYOFUINT32_COMM_DATALAYER_H_
