// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ARRAYOFFLOAT32_COMM_DATALAYER_H_
#define FLATBUFFERS_GENERATED_ARRAYOFFLOAT32_COMM_DATALAYER_H_

#include "flatbuffers/flatbuffers.h"

namespace comm {
namespace datalayer {

struct ArrayOfFloat32;
struct ArrayOfFloat32Builder;
struct ArrayOfFloat32T;

struct ArrayOfFloat32T : public flatbuffers::NativeTable {
  typedef ArrayOfFloat32 TableType;
  std::vector<float> value{};
};

struct ArrayOfFloat32 FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ArrayOfFloat32T NativeTableType;
  typedef ArrayOfFloat32Builder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<float> *value() const {
    return GetPointer<const flatbuffers::Vector<float> *>(VT_VALUE);
  }
  flatbuffers::Vector<float> *mutable_value() {
    return GetPointer<flatbuffers::Vector<float> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyVector(value()) &&
           verifier.EndTable();
  }
  ArrayOfFloat32T *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ArrayOfFloat32T *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<ArrayOfFloat32> Pack(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfFloat32T* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ArrayOfFloat32Builder {
  typedef ArrayOfFloat32 Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<float>> value) {
    fbb_.AddOffset(ArrayOfFloat32::VT_VALUE, value);
  }
  explicit ArrayOfFloat32Builder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ArrayOfFloat32> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ArrayOfFloat32>(end);
    return o;
  }
};

inline flatbuffers::Offset<ArrayOfFloat32> CreateArrayOfFloat32(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<float>> value = 0) {
  ArrayOfFloat32Builder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<ArrayOfFloat32> CreateArrayOfFloat32Direct(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *value = nullptr) {
  auto value__ = value ? _fbb.CreateVector<float>(*value) : 0;
  return comm::datalayer::CreateArrayOfFloat32(
      _fbb,
      value__);
}

flatbuffers::Offset<ArrayOfFloat32> CreateArrayOfFloat32(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfFloat32T *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline ArrayOfFloat32T *ArrayOfFloat32::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ArrayOfFloat32T>(new ArrayOfFloat32T());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ArrayOfFloat32::UnPackTo(ArrayOfFloat32T *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = value(); if (_e) { _o->value.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->value[_i] = _e->Get(_i); } } }
}

inline flatbuffers::Offset<ArrayOfFloat32> ArrayOfFloat32::Pack(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfFloat32T* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateArrayOfFloat32(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<ArrayOfFloat32> CreateArrayOfFloat32(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfFloat32T *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const ArrayOfFloat32T* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _value = _o->value.size() ? _fbb.CreateVector(_o->value) : 0;
  return comm::datalayer::CreateArrayOfFloat32(
      _fbb,
      _value);
}

inline const comm::datalayer::ArrayOfFloat32 *GetArrayOfFloat32(const void *buf) {
  return flatbuffers::GetRoot<comm::datalayer::ArrayOfFloat32>(buf);
}

inline const comm::datalayer::ArrayOfFloat32 *GetSizePrefixedArrayOfFloat32(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<comm::datalayer::ArrayOfFloat32>(buf);
}

inline ArrayOfFloat32 *GetMutableArrayOfFloat32(void *buf) {
  return flatbuffers::GetMutableRoot<ArrayOfFloat32>(buf);
}

inline bool VerifyArrayOfFloat32Buffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<comm::datalayer::ArrayOfFloat32>(nullptr);
}

inline bool VerifySizePrefixedArrayOfFloat32Buffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<comm::datalayer::ArrayOfFloat32>(nullptr);
}

inline void FinishArrayOfFloat32Buffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<comm::datalayer::ArrayOfFloat32> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedArrayOfFloat32Buffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<comm::datalayer::ArrayOfFloat32> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<comm::datalayer::ArrayOfFloat32T> UnPackArrayOfFloat32(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<comm::datalayer::ArrayOfFloat32T>(GetArrayOfFloat32(buf)->UnPack(res));
}

inline std::unique_ptr<comm::datalayer::ArrayOfFloat32T> UnPackSizePrefixedArrayOfFloat32(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<comm::datalayer::ArrayOfFloat32T>(GetSizePrefixedArrayOfFloat32(buf)->UnPack(res));
}

}  // namespace datalayer
}  // namespace comm

#endif  // FLATBUFFERS_GENERATED_ARRAYOFFLOAT32_COMM_DATALAYER_H_
