// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ARRAYOFINT64_COMM_DATALAYER_H_
#define FLATBUFFERS_GENERATED_ARRAYOFINT64_COMM_DATALAYER_H_

#include "flatbuffers/flatbuffers.h"

namespace comm {
namespace datalayer {

struct ArrayOfInt64;
struct ArrayOfInt64Builder;
struct ArrayOfInt64T;

struct ArrayOfInt64T : public flatbuffers::NativeTable {
  typedef ArrayOfInt64 TableType;
  std::vector<int64_t> value{};
};

struct ArrayOfInt64 FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ArrayOfInt64T NativeTableType;
  typedef ArrayOfInt64Builder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<int64_t> *value() const {
    return GetPointer<const flatbuffers::Vector<int64_t> *>(VT_VALUE);
  }
  flatbuffers::Vector<int64_t> *mutable_value() {
    return GetPointer<flatbuffers::Vector<int64_t> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyVector(value()) &&
           verifier.EndTable();
  }
  ArrayOfInt64T *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ArrayOfInt64T *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<ArrayOfInt64> Pack(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfInt64T* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ArrayOfInt64Builder {
  typedef ArrayOfInt64 Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<int64_t>> value) {
    fbb_.AddOffset(ArrayOfInt64::VT_VALUE, value);
  }
  explicit ArrayOfInt64Builder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ArrayOfInt64> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ArrayOfInt64>(end);
    return o;
  }
};

inline flatbuffers::Offset<ArrayOfInt64> CreateArrayOfInt64(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<int64_t>> value = 0) {
  ArrayOfInt64Builder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<ArrayOfInt64> CreateArrayOfInt64Direct(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<int64_t> *value = nullptr) {
  auto value__ = value ? _fbb.CreateVector<int64_t>(*value) : 0;
  return comm::datalayer::CreateArrayOfInt64(
      _fbb,
      value__);
}

flatbuffers::Offset<ArrayOfInt64> CreateArrayOfInt64(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfInt64T *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline ArrayOfInt64T *ArrayOfInt64::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ArrayOfInt64T>(new ArrayOfInt64T());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ArrayOfInt64::UnPackTo(ArrayOfInt64T *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = value(); if (_e) { _o->value.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->value[_i] = _e->Get(_i); } } }
}

inline flatbuffers::Offset<ArrayOfInt64> ArrayOfInt64::Pack(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfInt64T* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateArrayOfInt64(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<ArrayOfInt64> CreateArrayOfInt64(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfInt64T *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const ArrayOfInt64T* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _value = _o->value.size() ? _fbb.CreateVector(_o->value) : 0;
  return comm::datalayer::CreateArrayOfInt64(
      _fbb,
      _value);
}

inline const comm::datalayer::ArrayOfInt64 *GetArrayOfInt64(const void *buf) {
  return flatbuffers::GetRoot<comm::datalayer::ArrayOfInt64>(buf);
}

inline const comm::datalayer::ArrayOfInt64 *GetSizePrefixedArrayOfInt64(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<comm::datalayer::ArrayOfInt64>(buf);
}

inline ArrayOfInt64 *GetMutableArrayOfInt64(void *buf) {
  return flatbuffers::GetMutableRoot<ArrayOfInt64>(buf);
}

inline bool VerifyArrayOfInt64Buffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<comm::datalayer::ArrayOfInt64>(nullptr);
}

inline bool VerifySizePrefixedArrayOfInt64Buffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<comm::datalayer::ArrayOfInt64>(nullptr);
}

inline void FinishArrayOfInt64Buffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<comm::datalayer::ArrayOfInt64> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedArrayOfInt64Buffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<comm::datalayer::ArrayOfInt64> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<comm::datalayer::ArrayOfInt64T> UnPackArrayOfInt64(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<comm::datalayer::ArrayOfInt64T>(GetArrayOfInt64(buf)->UnPack(res));
}

inline std::unique_ptr<comm::datalayer::ArrayOfInt64T> UnPackSizePrefixedArrayOfInt64(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<comm::datalayer::ArrayOfInt64T>(GetSizePrefixedArrayOfInt64(buf)->UnPack(res));
}

}  // namespace datalayer
}  // namespace comm

#endif  // FLATBUFFERS_GENERATED_ARRAYOFINT64_COMM_DATALAYER_H_
