// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_INT64_COMM_DATALAYER_H_
#define FLATBUFFERS_GENERATED_INT64_COMM_DATALAYER_H_

#include "flatbuffers/flatbuffers.h"

namespace comm {
namespace datalayer {

struct Int64;
struct Int64Builder;
struct Int64T;

struct Int64T : public flatbuffers::NativeTable {
  typedef Int64 TableType;
  int64_t value = 0;
};

struct Int64 FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef Int64T NativeTableType;
  typedef Int64Builder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  int64_t value() const {
    return GetField<int64_t>(VT_VALUE, 0);
  }
  bool mutate_value(int64_t _value) {
    return SetField<int64_t>(VT_VALUE, _value, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_VALUE) &&
           verifier.EndTable();
  }
  Int64T *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(Int64T *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<Int64> Pack(flatbuffers::FlatBufferBuilder &_fbb, const Int64T* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct Int64Builder {
  typedef Int64 Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(int64_t value) {
    fbb_.AddElement<int64_t>(Int64::VT_VALUE, value, 0);
  }
  explicit Int64Builder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Int64> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Int64>(end);
    return o;
  }
};

inline flatbuffers::Offset<Int64> CreateInt64(
    flatbuffers::FlatBufferBuilder &_fbb,
    int64_t value = 0) {
  Int64Builder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

flatbuffers::Offset<Int64> CreateInt64(flatbuffers::FlatBufferBuilder &_fbb, const Int64T *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline Int64T *Int64::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<Int64T>(new Int64T());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Int64::UnPackTo(Int64T *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = value(); _o->value = _e; }
}

inline flatbuffers::Offset<Int64> Int64::Pack(flatbuffers::FlatBufferBuilder &_fbb, const Int64T* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateInt64(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<Int64> CreateInt64(flatbuffers::FlatBufferBuilder &_fbb, const Int64T *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const Int64T* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _value = _o->value;
  return comm::datalayer::CreateInt64(
      _fbb,
      _value);
}

inline const comm::datalayer::Int64 *GetInt64(const void *buf) {
  return flatbuffers::GetRoot<comm::datalayer::Int64>(buf);
}

inline const comm::datalayer::Int64 *GetSizePrefixedInt64(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<comm::datalayer::Int64>(buf);
}

inline Int64 *GetMutableInt64(void *buf) {
  return flatbuffers::GetMutableRoot<Int64>(buf);
}

inline bool VerifyInt64Buffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<comm::datalayer::Int64>(nullptr);
}

inline bool VerifySizePrefixedInt64Buffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<comm::datalayer::Int64>(nullptr);
}

inline void FinishInt64Buffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<comm::datalayer::Int64> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedInt64Buffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<comm::datalayer::Int64> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<comm::datalayer::Int64T> UnPackInt64(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<comm::datalayer::Int64T>(GetInt64(buf)->UnPack(res));
}

inline std::unique_ptr<comm::datalayer::Int64T> UnPackSizePrefixedInt64(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<comm::datalayer::Int64T>(GetSizePrefixedInt64(buf)->UnPack(res));
}

}  // namespace datalayer
}  // namespace comm

#endif  // FLATBUFFERS_GENERATED_INT64_COMM_DATALAYER_H_
