// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RAW_COMM_DATALAYER_H_
#define FLATBUFFERS_GENERATED_RAW_COMM_DATALAYER_H_

#include "flatbuffers/flatbuffers.h"

namespace comm {
namespace datalayer {

struct Raw;
struct RawBuilder;
struct RawT;

struct RawT : public flatbuffers::NativeTable {
  typedef Raw TableType;
  std::vector<int8_t> value{};
};

struct Raw FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef RawT NativeTableType;
  typedef RawBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<int8_t> *value() const {
    return GetPointer<const flatbuffers::Vector<int8_t> *>(VT_VALUE);
  }
  flatbuffers::Vector<int8_t> *mutable_value() {
    return GetPointer<flatbuffers::Vector<int8_t> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyVector(value()) &&
           verifier.EndTable();
  }
  RawT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(RawT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<Raw> Pack(flatbuffers::FlatBufferBuilder &_fbb, const RawT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct RawBuilder {
  typedef Raw Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<int8_t>> value) {
    fbb_.AddOffset(Raw::VT_VALUE, value);
  }
  explicit RawBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Raw> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Raw>(end);
    return o;
  }
};

inline flatbuffers::Offset<Raw> CreateRaw(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<int8_t>> value = 0) {
  RawBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<Raw> CreateRawDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<int8_t> *value = nullptr) {
  auto value__ = value ? _fbb.CreateVector<int8_t>(*value) : 0;
  return comm::datalayer::CreateRaw(
      _fbb,
      value__);
}

flatbuffers::Offset<Raw> CreateRaw(flatbuffers::FlatBufferBuilder &_fbb, const RawT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline RawT *Raw::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<RawT>(new RawT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Raw::UnPackTo(RawT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = value(); if (_e) { _o->value.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->value.begin()); } }
}

inline flatbuffers::Offset<Raw> Raw::Pack(flatbuffers::FlatBufferBuilder &_fbb, const RawT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateRaw(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<Raw> CreateRaw(flatbuffers::FlatBufferBuilder &_fbb, const RawT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const RawT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _value = _o->value.size() ? _fbb.CreateVector(_o->value) : 0;
  return comm::datalayer::CreateRaw(
      _fbb,
      _value);
}

inline const comm::datalayer::Raw *GetRaw(const void *buf) {
  return flatbuffers::GetRoot<comm::datalayer::Raw>(buf);
}

inline const comm::datalayer::Raw *GetSizePrefixedRaw(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<comm::datalayer::Raw>(buf);
}

inline Raw *GetMutableRaw(void *buf) {
  return flatbuffers::GetMutableRoot<Raw>(buf);
}

inline bool VerifyRawBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<comm::datalayer::Raw>(nullptr);
}

inline bool VerifySizePrefixedRawBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<comm::datalayer::Raw>(nullptr);
}

inline void FinishRawBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<comm::datalayer::Raw> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedRawBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<comm::datalayer::Raw> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<comm::datalayer::RawT> UnPackRaw(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<comm::datalayer::RawT>(GetRaw(buf)->UnPack(res));
}

inline std::unique_ptr<comm::datalayer::RawT> UnPackSizePrefixedRaw(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<comm::datalayer::RawT>(GetSizePrefixedRaw(buf)->UnPack(res));
}

}  // namespace datalayer
}  // namespace comm

#endif  // FLATBUFFERS_GENERATED_RAW_COMM_DATALAYER_H_
