// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_UINT16_COMM_DATALAYER_H_
#define FLATBUFFERS_GENERATED_UINT16_COMM_DATALAYER_H_

#include "flatbuffers/flatbuffers.h"

namespace comm {
namespace datalayer {

struct UInt16;
struct UInt16Builder;
struct UInt16T;

struct UInt16T : public flatbuffers::NativeTable {
  typedef UInt16 TableType;
  uint16_t value = 0;
};

struct UInt16 FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef UInt16T NativeTableType;
  typedef UInt16Builder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  uint16_t value() const {
    return GetField<uint16_t>(VT_VALUE, 0);
  }
  bool mutate_value(uint16_t _value) {
    return SetField<uint16_t>(VT_VALUE, _value, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_VALUE) &&
           verifier.EndTable();
  }
  UInt16T *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(UInt16T *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<UInt16> Pack(flatbuffers::FlatBufferBuilder &_fbb, const UInt16T* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct UInt16Builder {
  typedef UInt16 Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(uint16_t value) {
    fbb_.AddElement<uint16_t>(UInt16::VT_VALUE, value, 0);
  }
  explicit UInt16Builder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<UInt16> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<UInt16>(end);
    return o;
  }
};

inline flatbuffers::Offset<UInt16> CreateUInt16(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t value = 0) {
  UInt16Builder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

flatbuffers::Offset<UInt16> CreateUInt16(flatbuffers::FlatBufferBuilder &_fbb, const UInt16T *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline UInt16T *UInt16::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<UInt16T>(new UInt16T());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void UInt16::UnPackTo(UInt16T *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = value(); _o->value = _e; }
}

inline flatbuffers::Offset<UInt16> UInt16::Pack(flatbuffers::FlatBufferBuilder &_fbb, const UInt16T* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateUInt16(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<UInt16> CreateUInt16(flatbuffers::FlatBufferBuilder &_fbb, const UInt16T *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const UInt16T* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _value = _o->value;
  return comm::datalayer::CreateUInt16(
      _fbb,
      _value);
}

inline const comm::datalayer::UInt16 *GetUInt16(const void *buf) {
  return flatbuffers::GetRoot<comm::datalayer::UInt16>(buf);
}

inline const comm::datalayer::UInt16 *GetSizePrefixedUInt16(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<comm::datalayer::UInt16>(buf);
}

inline UInt16 *GetMutableUInt16(void *buf) {
  return flatbuffers::GetMutableRoot<UInt16>(buf);
}

inline bool VerifyUInt16Buffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<comm::datalayer::UInt16>(nullptr);
}

inline bool VerifySizePrefixedUInt16Buffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<comm::datalayer::UInt16>(nullptr);
}

inline void FinishUInt16Buffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<comm::datalayer::UInt16> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedUInt16Buffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<comm::datalayer::UInt16> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<comm::datalayer::UInt16T> UnPackUInt16(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<comm::datalayer::UInt16T>(GetUInt16(buf)->UnPack(res));
}

inline std::unique_ptr<comm::datalayer::UInt16T> UnPackSizePrefixedUInt16(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<comm::datalayer::UInt16T>(GetSizePrefixedUInt16(buf)->UnPack(res));
}

}  // namespace datalayer
}  // namespace comm

#endif  // FLATBUFFERS_GENERATED_UINT16_COMM_DATALAYER_H_
