// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_UINT8_COMM_DATALAYER_H_
#define FLATBUFFERS_GENERATED_UINT8_COMM_DATALAYER_H_

#include "flatbuffers/flatbuffers.h"

namespace comm {
namespace datalayer {

struct UInt8;
struct UInt8Builder;
struct UInt8T;

struct UInt8T : public flatbuffers::NativeTable {
  typedef UInt8 TableType;
  uint8_t value = 0;
};

struct UInt8 FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef UInt8T NativeTableType;
  typedef UInt8Builder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  uint8_t value() const {
    return GetField<uint8_t>(VT_VALUE, 0);
  }
  bool mutate_value(uint8_t _value) {
    return SetField<uint8_t>(VT_VALUE, _value, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_VALUE) &&
           verifier.EndTable();
  }
  UInt8T *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(UInt8T *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<UInt8> Pack(flatbuffers::FlatBufferBuilder &_fbb, const UInt8T* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct UInt8Builder {
  typedef UInt8 Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(uint8_t value) {
    fbb_.AddElement<uint8_t>(UInt8::VT_VALUE, value, 0);
  }
  explicit UInt8Builder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<UInt8> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<UInt8>(end);
    return o;
  }
};

inline flatbuffers::Offset<UInt8> CreateUInt8(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t value = 0) {
  UInt8Builder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

flatbuffers::Offset<UInt8> CreateUInt8(flatbuffers::FlatBufferBuilder &_fbb, const UInt8T *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline UInt8T *UInt8::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<UInt8T>(new UInt8T());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void UInt8::UnPackTo(UInt8T *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = value(); _o->value = _e; }
}

inline flatbuffers::Offset<UInt8> UInt8::Pack(flatbuffers::FlatBufferBuilder &_fbb, const UInt8T* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateUInt8(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<UInt8> CreateUInt8(flatbuffers::FlatBufferBuilder &_fbb, const UInt8T *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const UInt8T* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _value = _o->value;
  return comm::datalayer::CreateUInt8(
      _fbb,
      _value);
}

inline const comm::datalayer::UInt8 *GetUInt8(const void *buf) {
  return flatbuffers::GetRoot<comm::datalayer::UInt8>(buf);
}

inline const comm::datalayer::UInt8 *GetSizePrefixedUInt8(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<comm::datalayer::UInt8>(buf);
}

inline UInt8 *GetMutableUInt8(void *buf) {
  return flatbuffers::GetMutableRoot<UInt8>(buf);
}

inline bool VerifyUInt8Buffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<comm::datalayer::UInt8>(nullptr);
}

inline bool VerifySizePrefixedUInt8Buffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<comm::datalayer::UInt8>(nullptr);
}

inline void FinishUInt8Buffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<comm::datalayer::UInt8> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedUInt8Buffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<comm::datalayer::UInt8> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<comm::datalayer::UInt8T> UnPackUInt8(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<comm::datalayer::UInt8T>(GetUInt8(buf)->UnPack(res));
}

inline std::unique_ptr<comm::datalayer::UInt8T> UnPackSizePrefixedUInt8(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<comm::datalayer::UInt8T>(GetSizePrefixedUInt8(buf)->UnPack(res));
}

}  // namespace datalayer
}  // namespace comm

#endif  // FLATBUFFERS_GENERATED_UINT8_COMM_DATALAYER_H_
