// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ARRAYOFINT32_COMM_DATALAYER_H_
#define FLATBUFFERS_GENERATED_ARRAYOFINT32_COMM_DATALAYER_H_

#include "flatbuffers/flatbuffers.h"

namespace comm {
namespace datalayer {

struct ArrayOfInt32;
struct ArrayOfInt32Builder;
struct ArrayOfInt32T;

struct ArrayOfInt32T : public flatbuffers::NativeTable {
  typedef ArrayOfInt32 TableType;
  std::vector<int32_t> value{};
};

struct ArrayOfInt32 FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ArrayOfInt32T NativeTableType;
  typedef ArrayOfInt32Builder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<int32_t> *value() const {
    return GetPointer<const flatbuffers::Vector<int32_t> *>(VT_VALUE);
  }
  flatbuffers::Vector<int32_t> *mutable_value() {
    return GetPointer<flatbuffers::Vector<int32_t> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyVector(value()) &&
           verifier.EndTable();
  }
  ArrayOfInt32T *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ArrayOfInt32T *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<ArrayOfInt32> Pack(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfInt32T* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ArrayOfInt32Builder {
  typedef ArrayOfInt32 Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<int32_t>> value) {
    fbb_.AddOffset(ArrayOfInt32::VT_VALUE, value);
  }
  explicit ArrayOfInt32Builder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ArrayOfInt32> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ArrayOfInt32>(end);
    return o;
  }
};

inline flatbuffers::Offset<ArrayOfInt32> CreateArrayOfInt32(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<int32_t>> value = 0) {
  ArrayOfInt32Builder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<ArrayOfInt32> CreateArrayOfInt32Direct(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<int32_t> *value = nullptr) {
  auto value__ = value ? _fbb.CreateVector<int32_t>(*value) : 0;
  return comm::datalayer::CreateArrayOfInt32(
      _fbb,
      value__);
}

flatbuffers::Offset<ArrayOfInt32> CreateArrayOfInt32(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfInt32T *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline ArrayOfInt32T *ArrayOfInt32::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ArrayOfInt32T>(new ArrayOfInt32T());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ArrayOfInt32::UnPackTo(ArrayOfInt32T *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = value(); if (_e) { _o->value.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->value[_i] = _e->Get(_i); } } }
}

inline flatbuffers::Offset<ArrayOfInt32> ArrayOfInt32::Pack(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfInt32T* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateArrayOfInt32(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<ArrayOfInt32> CreateArrayOfInt32(flatbuffers::FlatBufferBuilder &_fbb, const ArrayOfInt32T *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const ArrayOfInt32T* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _value = _o->value.size() ? _fbb.CreateVector(_o->value) : 0;
  return comm::datalayer::CreateArrayOfInt32(
      _fbb,
      _value);
}

inline const comm::datalayer::ArrayOfInt32 *GetArrayOfInt32(const void *buf) {
  return flatbuffers::GetRoot<comm::datalayer::ArrayOfInt32>(buf);
}

inline const comm::datalayer::ArrayOfInt32 *GetSizePrefixedArrayOfInt32(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<comm::datalayer::ArrayOfInt32>(buf);
}

inline ArrayOfInt32 *GetMutableArrayOfInt32(void *buf) {
  return flatbuffers::GetMutableRoot<ArrayOfInt32>(buf);
}

inline bool VerifyArrayOfInt32Buffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<comm::datalayer::ArrayOfInt32>(nullptr);
}

inline bool VerifySizePrefixedArrayOfInt32Buffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<comm::datalayer::ArrayOfInt32>(nullptr);
}

inline void FinishArrayOfInt32Buffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<comm::datalayer::ArrayOfInt32> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedArrayOfInt32Buffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<comm::datalayer::ArrayOfInt32> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<comm::datalayer::ArrayOfInt32T> UnPackArrayOfInt32(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<comm::datalayer::ArrayOfInt32T>(GetArrayOfInt32(buf)->UnPack(res));
}

inline std::unique_ptr<comm::datalayer::ArrayOfInt32T> UnPackSizePrefixedArrayOfInt32(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<comm::datalayer::ArrayOfInt32T>(GetSizePrefixedArrayOfInt32(buf)->UnPack(res));
}

}  // namespace datalayer
}  // namespace comm

#endif  // FLATBUFFERS_GENERATED_ARRAYOFINT32_COMM_DATALAYER_H_
