name: python-ai-toolkit
version: 0.1.5.4
summary: Python AI starter kit
description: 'Simple Webbased Editor'

base: core20
confinement: strict
grade: stable

# Limit architectures as ppcel64 doesn't build currently
architectures:
  - build-on: amd64
  - build-on: arm64


apps:
  jupyter:
    command: bin/jupyter.wrapper
    daemon: simple
    plugs:
      - network-bind
      - network-status
      - network-observe
      - serial-port
      - datalayer
    environment:
      "LD_LIBRARY_PATH": "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/python3/dist-packages"
     
    
  desktop-launch:
    command: bin/desktop-launch
    plugs:
      - desktop  

parts:


  requests:
    plugin: python
    build-environment:
      - PYTHONPATH: "$SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages"

    stage-packages:
      - wget
      - git
      - zip 
      - libssl-dev
      - libcurl4-openssl-dev
      - libcurl-dev
      - pkg-config
      - build-essential
      - libpython3.8
      - libusb-1.0-0-dev
      - unzip
      - ffmpeg 
      - libglu1-mesa
      - freeglut3
      - libsm6 
      - libxext6 
      - python3-wheel
      
    python-packages:
      - wheel
      - requests
      - jupyterlab
      - jupyterlab-git
      - flask
      - werkzeug 
      - jwcrypto
      - six
      - autopep8
      - pandas
      - numpy
      - matplotlib
      - ctrlx_fbs
      - ctrlx_datalayer
      - landingai


    build-packages:
      - python3-dev
      - python3-wheel
      - build-essential
      - python3-setuptools

  mylib:
    plugin: nil
    source: ./mywheels
    build-packages:
      - python3-dev
      - python3-wheel
      - build-essential
      - python3-setuptools

    after:
      - requests
    override-build: |
        echo $SNAPCRAFT_ARCH_TRIPLET
        case "$SNAPCRAFT_ARCH_TRIPLET" in
          *aarch64*)
              WHEEL_FILE="neoapi-1.3.0-cp38-cp38-linux_aarch64.whl" ;;
          *x86_64*)
              WHEEL_FILE="neoapi-1.3.0-cp38-cp38-linux_x86_64.whl" ;;
          *)
              echo "Unsupported architecture!"
              exit 1 ;;
        esac
        ls
        #python3 -m venv  $SNAPCRAFT_PART_INSTALL 
        python3 -m pip install  --no-cache-dir -I $WHEEL_FILE -t $SNAPCRAFT_PART_INSTALL/mylibs
        cp $SNAPCRAFT_PART_INSTALL/mylibs/neoapi/_neoapi.so $SNAPCRAFT_PART_INSTALL/mylibs/neoapi/_neoapi

        snapcraftctl stage

    stage-packages:
      - libpython3.8
      - libusb-1.0-0-dev

  datalayerdeb:
      plugin: dump
      source: https://github.com/boschrexroth/ctrlx-automation-sdk/releases/download/1.18.0/ctrlx-datalayer-1.9.1.deb
      source-type: deb
      stage-packages:
        - libzmq5
     
 
 
  shscripts:  
    source: ./shscripts/
    plugin: dump
    organize:
      '*': bin/
      

  configs:
    source: ./configs
    plugin: dump
    organize:
      'package-assets/*': package-assets/${SNAPCRAFT_PROJECT_NAME}/
      'secure-assets/*': secure-assets/${SNAPCRAFT_PROJECT_NAME}/



plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer 


slots:
  secure-assets:
    interface: content
    content: secure-assets
    source:
      read:
        - $SNAP/secure-assets/${SNAPCRAFT_PROJECT_NAME}

  service-token:
    interface: content
    content: service-token
    source:
      write:
        - $SNAP_DATA/service-token/${SNAPCRAFT_PROJECT_NAME}

  package-assets:
    interface: content
    content: package-assets
    source:
      read:
        - $SNAP/package-assets/${SNAPCRAFT_PROJECT_NAME}