name: python-ai-toolkit
version: 0.1.5.4
summary: Python AI starter kit
description: 'Simple Webbased Editor'

base: core20
confinement: strict
grade: stable

# Limit architectures as ppcel64 doesn't build currently
architectures:
  - build-on: amd64
  - build-on: arm64


apps:
  jupyter:
    command: bin/jupyter.wrapper
    daemon: simple
    plugs:
      - network-bind
      - network-status
      - network-observe
      - serial-port
      - datalayer
    environment:
       "LD_LIBRARY_PATH": "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/python3/dist-packages"
      

    
  desktop-launch:
    command: bin/desktop-launch
    plugs:
      - desktop  

parts:


  requests:
    plugin: python
    build-environment:
      - PYTHONPATH: "$SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages"

    stage-packages:
      - libzbar0
      - libzbar-dev
      - libfreetype6-dev
      - wget
      - git
      - libssl-dev
      - libcurl4-openssl-dev
      - libcurl-dev
      - pkg-config
      - libpng-dev
      - python3-opencv
      - python3-grpcio
      - ffmpeg
      - unzip
      - python3-wheel
      - libatlas-base-dev
      
    python-packages:
      - python-ffmpeg
      - wheel
      - requests
      - pyserial
      - pillow
      - flask
      - pymongo
      - gitpython
      - appdirs
      - influxdb
      - imutils 
      - werkzeug
      - bokeh
      - jupyterlab
      - jupyterlab-git
      - jupyterlab-system-monitor
      - jupyterlab-zip
      - numpy
      - six
      - autopep8
      - ctrlx_fbs
      - ctrlx_datalayer
      - python-socketio[client]
      - scikit-learn
      - scipy
      - opencv-python
      - schedule 
      - pandas
      - matplotlib
      - typer
      - tsfresh
      - pydantic
      - azure-iot-device
      - colorama
      - asyncua

    build-packages:
      - python3-dev
      - python3-wheel
      - build-essential
      - python3-setuptools
      - libzbar0
      - libzbar-dev
      - libatlas-base-dev



  datalayerdeb:
      plugin: dump
      source: https://github.com/boschrexroth/ctrlx-automation-sdk/releases/download/1.18.0/ctrlx-datalayer-1.9.1.deb
      source-type: deb
      stage-packages:
        - libzmq5
     
 
 
  shscripts:  
    source: ./shscripts/
    plugin: dump
    organize:
      '*': bin/
      

  configs:
    source: ./configs
    plugin: dump
    organize:
      'package-assets/*': package-assets/${SNAPCRAFT_PROJECT_NAME}/

plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer 
